name: Rust

on:
  push

env:
  CARGO_TERM_COLOR: always

jobs:
  linux_x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup latest Alpine linux
      uses: jirutka/setup-alpine@v1.2.0
    - name: Prepare Alpine chroot
      run: |
        apk add git curl bash g++ musl-dev make perl
        curl -sSf https://sh.rustup.rs | bash -s -- -y
      shell: alpine.sh --root {0}
    - name: Build in Alpine chroot
      run: cargo build --release
      shell: alpine.sh --root {0}
    - name: Run tests
      run: cargo test --release --verbose
      shell: alpine.sh --root {0}
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: log_to_network Linux x86_64
        path: target/release/log_to_network
    - name: Archive
      uses: thedoctor0/zip-release@0.7.5
      if: startsWith(github.ref, 'refs/tags/')
      with:
        type: tar
        filename: ../../log_to_network-linux-x86_64-${{ github.ref_name }}.tar.gz
        directory: target/release
        path: log_to_network
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: log_to_network-linux-x86_64-${{ github.ref_name }}.tar.gz

  macos:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --release --verbose
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: log_to_network macOS Intel
        path: target/release/log_to_network
    - name: Archive
      uses: thedoctor0/zip-release@0.7.5
      if: startsWith(github.ref, 'refs/tags/')
      with:
        type: tar
        filename: ../../log_to_network-macos-x86_64-${{ github.ref_name }}.tar.gz
        directory: target/release
        path: log_to_network
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: log_to_network-macos-x86_64-${{ github.ref_name }}.tar.gz

  macos_arm64:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --release --verbose
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: log_to_network macOS Apple Silicon
        path: target/release/log_to_network
    - name: Archive
      uses: thedoctor0/zip-release@0.7.5
      if: startsWith(github.ref, 'refs/tags/')
      with:
        type: tar
        filename: ../../log_to_network-macos-aarch64-${{ github.ref_name }}.tar.gz
        directory: target/release
        path: log_to_network
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: log_to_network-macos-aarch64-${{ github.ref_name }}.tar.gz

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --release --verbose
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: log_to_network Windows x86_64
        path: target/release/log_to_network.exe
    - name: Archive
      uses: thedoctor0/zip-release@0.7.5
      if: startsWith(github.ref, 'refs/tags/')
      with:
        type: zip
        filename: ../../log_to_network-windows-x86_64-${{ github.ref_name }}.zip
        directory: target/release
        path: log_to_network.exe
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: log_to_network-windows-x86_64-${{ github.ref_name }}.zip
